### PR TITLE
Adhere to `event.defaultPrevented` on form submit events

### PR DESCRIPTION
**Pull request by runarberg**
Fixes: #191

### CODE REVIEW

**Comment by runarberg** [comment]
@googlebot I signed it!

**Comment by samthor** [comment]
Thank you!

**Comment by runarberg** [comment]
Is there an ETA for when this gets published in a new version?

**Comment by samthor** [comment]
Hi, probably when I get time next week after Chrome Dev Summit.

**Comment by runarberg** [comment]
Just seeing if you plan on releasing a patch soon?

**Pull request merged**
