### PR TITLE
Add JSFiddle link

### PR DESCRIPTION
**Pull request by ArtskydJ**
Added a link to a JSFiddle so people can try out the example!

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Signed.

**Comment by ArtskydJ** [comment]
You're welcome. :smile:

**Comment by ArtskydJ** [comment]
You're welcome. :smile:

**Comment by ArtskydJ** [comment]
@GoogleChrome bump...

**Comment by Garbee** [comment]
PR #86 landed. That seems to fulfill this need and is more detailed than a jsfiddle.

**Pull request closed without merging**
