### PR TITLE
fixed: focusing steps run both on showModal() and show() call

### LINKED ISSUE #33: Shouldn't focusing be done on show()?
As both [WHATWG](https://html.spec.whatwg.org/multipage/forms.html#the-dialog-element) and [W3](http://www.w3.org/html/wg/drafts/html/master/interactive-elements.html#the-dialog-element) says, dialog focusing steps should be performed both on show() and showModal() calls, but polyfill performes them only on showModal() call.

### PR DESCRIPTION
**Pull request by ThiRaBrTNK**
resolves #33

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM

**Comment by samthor** [comment]
This will cause focus to be triggered _every_ time `.show()` is called, which I don't think matches the spec. It should instead only focus when first made visible.

**Comment by samthor** [comment]
See #101.

**Comment by ThiRaBrTNK** [comment]
You are right, thanks

**Pull request closed without merging**
