### PR TITLE
Fix types for ESM

### PR DESCRIPTION
**Pull request by qurben**
Fixes GoogleChrome/dialog-polyfill#204

Should not have an impact on the cjs types.

### CODE REVIEW

**Comment by qurben** [comment]
@googlebot I signed it!

**Comment by samthor** [comment]
So I confess I haven't been paying that much attention to the other issue. I appreciate that there is a problem, but I am confused. The dist esm file has this line in it:

```js
export default dialogPolyfill;
```

That's literally the default export. It seems like this PR just adds another variable _called_ `dialogPolyfill` of the core type. But we don't export that; we export a default.

**Comment by qurben** [comment]
I missed a line when applying my changes, sorry!

The created variable should be exported as the default. This tells Typescript that a value is exported an not a type.

**Comment by samthor** [comment]
Thanks. I'm learning about TS types vs variables too from this. I'll release an update soon.

**Pull request merged**
